headline:    The Blog Headline
description: The Blog Descrption
siteUrl:     http://www.your-blog.de/
language:    en
dataDir:     /data
tplDir:      /templates
htdocs:      /htdocs
twitter:
	consumer_key:       ''
    consumer_secret:    ''
    oauth_token:        ''
    oauth_token_secret: ''
bitly:
    username: ''
    apikey:   ''
api:
  url: http://www.your-blog.de/api/
features:
  rating: false